// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnjYUkba2ERqnnZ3JZfswqyQ5ch-SjTE',
    appId: '1:377283793239:web:9f3581c7d552de725c2e12',
    messagingSenderId: '377283793239',
    projectId: 'harcama-takip-uygulamasi-bec2c',
    authDomain: 'harcama-takip-uygulamasi-bec2c.firebaseapp.com',
    storageBucket: 'harcama-takip-uygulamasi-bec2c.firebasestorage.app',
    measurementId: 'G-TSHE63CDT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgVKyiBJMfQhgtWxX9zQSaMpP-A1v4Pg',
    appId: '1:377283793239:android:1ddfb93fd8c6ef385c2e12',
    messagingSenderId: '377283793239',
    projectId: 'harcama-takip-uygulamasi-bec2c',
    storageBucket: 'harcama-takip-uygulamasi-bec2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdsRiJmN2djZlgJNvP1Q9YbgyHXC2QI0',
    appId: '1:377283793239:ios:4b8b6745c90a50825c2e12',
    messagingSenderId: '377283793239',
    projectId: 'harcama-takip-uygulamasi-bec2c',
    storageBucket: 'harcama-takip-uygulamasi-bec2c.firebasestorage.app',
    iosBundleId: 'com.example.harcamaTakipUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdsRiJmN2djZlgJNvP1Q9YbgyHXC2QI0',
    appId: '1:377283793239:ios:4b8b6745c90a50825c2e12',
    messagingSenderId: '377283793239',
    projectId: 'harcama-takip-uygulamasi-bec2c',
    storageBucket: 'harcama-takip-uygulamasi-bec2c.firebasestorage.app',
    iosBundleId: 'com.example.harcamaTakipUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgnjYUkba2ERqnnZ3JZfswqyQ5ch-SjTE',
    appId: '1:377283793239:web:b2bc346989a171615c2e12',
    messagingSenderId: '377283793239',
    projectId: 'harcama-takip-uygulamasi-bec2c',
    authDomain: 'harcama-takip-uygulamasi-bec2c.firebaseapp.com',
    storageBucket: 'harcama-takip-uygulamasi-bec2c.firebasestorage.app',
    measurementId: 'G-BWZ1Q0JMR3',
  );
}
